### PR TITLE
MCKIN-7741-DnDv4 theme changes for item bank

### PR DESCRIPTION
**Pull request by murad-hubib**
- Added colors for mckinsey theme for DnD item bank
Related ticket: https://edx-wiki.atlassian.net/browse/MCKIN-7741

@bradenmacdonald @xitij2000 Please review this PR & Merge

### CODE REVIEW

**Comment by pomegranited** [comment]
@murad-hubib  I'll be reviewing this tomorrow.  Could you please rebase this on the latest `mckinseyacademy:master` to resolve the conflict above?

**Comment by kaizoku** [comment]
@murad-hubib `$mckinsey-royal-blue` isn't set, but it will be after rebasing on master and fixing the conflict.

Also I'm not seeing the arrows to the right and left of the items. It shows the default bx slider text of "Prev" and "Next", and the controls are beneath the items, rather than surrounding them.
I'm not sure if this can be changed from the theme. It can be selected using the `prevText` and `nextText` options described in the [bxslider options docs](https://bxslider.com/options/).

Also the "dropped" class is not being set for items that are placed, so they still show up in the selectable items. Is adding this code planned for a PR to edx-solutions/xblock-drag-and-drop ?

**Comment by murad-hubib** [comment]
@pomegranited Yes the tests are being handled in DNDv4 on xblock side. This PR is related to theme colours only.

**Comment by murad-hubib** [comment]
@kaizoku I have resolved the color variable conflict. And for arrows and dropped class you need to have the changes of this [PR](https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/166). But the PR is not yet merged so either you can wait for that or you can take changes from branch "MCKIN-7636-7638-7741-slider-styling" to test the changes of this PR.

**Comment by kaizoku** [comment]
Thanks for fixing the merge conflic @murad-hubib .
I tested with the `MCKIN-7636-7638-7741-slider-styling` branch and that fixes the issues above.

:+1:

- [✓] I tested this: (deployed in devstack and examined rendered XBlock)
- [✓] I read through the code
- [✓] I checked for accessibility issues
- [n/a] Includes documentation

**Comment by murad-hubib** [comment]
@kaizoku We need to revert this PR against master branch as we are getting these new changes in old DND. I will create then a new PR with this changes against a temp branch that we will merge to master once we merge the drag-and-drop-v4 braqnch to master. 

I am unable to create a PR to revert this PR. Can you please revert this PR?

**Comment by xitij2000** [comment]
@murad-hubib  I don't see a revert option either. Could you create another PR that manually reverts this change? Ping me on it and I will check and merge it.

**Pull request merged**
