### PR TITLE
Adventure xblock

### PR DESCRIPTION
**Pull request by prakashpathak02**

### CODE REVIEW

**Comment by prakashpathak02** [comment]
@furqan-ud-din @murad-hubib @shahidrafique @msaqib52 please review and merge

**Comment by murad-hubib** [comment]
@msaqib52 Please review JS changes 
@shahidrafique Please review SCSS

**Comment by nasirhjafri** [comment]
@prakashpathak02 Can you please mention the changes you made in this PR and why you made it in the description? It would be easier to review in that way.

**Comment by prakashpathak02** [comment]
@nasirhjafri This is for responsiveness and new ui for adventure xblock - https://edx-wiki.atlassian.net/browse/MCKIN-9112

**Comment by nasirhjafri** [comment]
@shahidrafique Kindly review SCSS

**Pull request merged**
