### PR TITLE
MCKIN-7636 & MCKIN-7638 Theme for right and wrong popup for V4

### PR DESCRIPTION
**Pull request by murad-hubib**
- Added theme for wrong and right poup

Tikects: 
[https://edx-wiki.atlassian.net/browse/MCKIN-7636](https://edx-wiki.atlassian.net/browse/MCKIN-7636)
[https://edx-wiki.atlassian.net/browse/MCKIN-7638](https://edx-wiki.atlassian.net/browse/MCKIN-7638)

@kaizoku Please review and merge

CC: @bradenmacdonald  @xitij2000

### CODE REVIEW

**Comment by kaizoku** [comment]
@murad-hubib Just FYI, I'm still waiting on the PR to drag-and-drop-v2 to test this out.
Unless I'm mistaken these theming changes will have to be tested in the context of the updates to that XBlock.

**Comment by murad-hubib** [comment]
@kaizoku Yes you are right that changes need to be merged before you review this PR. I will mention dependencies (if any) in PRs in future.

**Comment by kaizoku** [comment]
@murad-hubib 
When a correct selection is made, the "Select Another Item" text runs underneath the right arrow that should be next to it. and the arrow isn't centered in the button.

Also, the reset button at the bottom isn't centered in its container, and there's a line on the right side which looks out of place, but the reset button isn't in the screenshots, so I'm not sure how that is supposed to look.

screenshot_2018-09-14 the chamber of secrets lessons mckinsey academy


Once a selection is made, the placeholders for selections already made are then  misaligned with the rest of them, and it changes the size and skews the whole selection box at the bottom.

screenshot_2018-09-14 the chamber of secrets lessons mckinsey academy 1

**Comment by murad-hubib** [comment]
@kaizoku The button is looking fine (doen't overlap) in my APROS however I have increased its size. All other issues are not related to this PR. They are being fixed in other/relevant PRs

**Comment by kaizoku** [comment]
@murad-hubib Ah yep, those issues weren't introduced by this PR so it's not exactly a part of fixing them here. Thanks for letting me know.

:+1:

- [✓] I tested this: (deployed in devstack, tested drag and drop with theme enabled) 
- [✓] I read through the code
- [✓] I checked for accessibility issues
~- [n/a] Includes documentation~

**Pull request merged**
