### PR TITLE
Revert "xblock responsive newui polls & discussions"

### PR DESCRIPTION
**Pull request by prakashpathak02**
Reverts mckinseyacademy/mcka-theme#39

### CODE REVIEW

**Comment by nasirhjafri** [comment]
Hi @prakashpathak02 Can you please change the base branch to development?

**Comment by prakashpathak02** [comment]
Hi @nasirhjafri , this is to revert PR merge that was done on master instead of development, this will go in master branch only.

**Comment by nasirhjafri** [comment]
Ah thanks for explaining. @murad-hubib Can you please review it?

**Comment by murad-hubib** [comment]
@prakashpathak02 Please remove conflicts first

**Pull request closed without merging**
